### ISSUE TITLE
Fails to run "azd provision" in section "adding a custom domain name"

### ISSUE THREAD

**Issue by NanaXiong00** [CMeeg/nextjs-aca#4]
**Describe the issue:**
An error occurred while running `azd provision` according to the "adding a custom domain name" section of [README.md](https://github.com/CMeeg/nextjs-aca#adding-a-custom-domain-name). The error is shown as following:
<img width="607" alt="image" src="https://github.com/CMeeg/nextjs-aca/assets/138103031/0b2094fc-c370-4983-956a-d48c00e1dce5">

**Repro Steps:**
1. Run `npm i`
2. Run `npm run env:init`
3. Run `azd auth login`
4. Add `SERVICE_WEB_CUSTOM_DOMAIN_NAME=www.xshtest.com` in `.env.local` file
5. Run `azd provision`

**Expected behavior:**
Run command `azd provision` successfully.

@CMeeg and @hemarina for notification.

**Comment by CMeeg** [comment]
Thanks for flagging this. I already had some DNS records setup where I had been testing the template that meant the domain verification step was passing.

I removed the DNS records and was able to reproduce the error that you raised.

I have now updated the readme (3fe3673) with some further instruction of how to verify your custom domain before you add it to the container app.
